//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIKE_LOCAL
    {
        public int ID { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_GENERO { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual GENERO GENERO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
