//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE_GENERO
    {
        public int ID { get; set; }
        public int ID_MOVIE { get; set; }
        public int ID_GENERO { get; set; }
    
        public virtual GENERO GENERO { get; set; }
        public virtual MOVIE MOVIE { get; set; }
    }
}
