//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE()
        {
            this.EVENTO = new HashSet<EVENTO>();
            this.LIKE_MOVIES = new HashSet<LIKE_MOVIES>();
            this.MOVIE_GENERO = new HashSet<MOVIE_GENERO>();
            this.POSTAGEM = new HashSet<POSTAGEM>();
        }
    
        public int ID { get; set; }
        public int ID_CRIADOR_PAGINA { get; set; }
        public string TITULO { get; set; }
        public int TIPO { get; set; }
        public Nullable<int> TEMPORADAS { get; set; }
        public Nullable<int> EPISODIOS { get; set; }
        public Nullable<System.TimeSpan> DURACAO { get; set; }
        public string CLASSIFICACAO { get; set; }
        public string LINK_FOTO_CAPA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIKE_MOVIES> LIKE_MOVIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIE_GENERO> MOVIE_GENERO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTAGEM> POSTAGEM { get; set; }
    }
}
