CREATE TABLE [dbo].[CONTATO]
(
	[ID] INT NOT NULL  IDENTITY(1, 1), 
    [ID_USUARIO1] INT NOT NULL, 
    [ID_USUARIO2] INT NOT NULL, 
    [STATUS] INT NOT NULL, 
    CONSTRAINT [FK_CONTATOS_USUARIOS] FOREIGN KEY ([ID_USUARIO1]) REFERENCES [USUARIO]([ID]), 
    CONSTRAINT [FK_CONTATOS_USUARIOS2] FOREIGN KEY ([ID_USUARIO2]) REFERENCES [USUARIO]([ID]), 
    PRIMARY KEY ([ID_USUARIO1], [ID_USUARIO2])
)
