CREATE TABLE [dbo].[EVENTO]
(
	[ID] INT NOT NULL  IDENTITY(1, 1), 
    [ID_MOVIE] INT NOT NULL, 
    [ID_LOCAL] INT NOT NULL,
    [DESCRICAO] VARCHAR(MAX) NULL, 
    PRIMARY KEY ([ID]),
	UNIQUE ([ID_MOVIE], [ID_LOCAL]),
    CONSTRAINT [FK_MOVIE_LOCAL_MOVIE] FOREIGN KEY ([ID_MOVIE]) REFERENCES [MOVIE]([ID]), 
    CONSTRAINT [FK_MOVIE_LOCAL_LOCAL] FOREIGN KEY ([ID_LOCAL]) REFERENCES [LOCAL]([ID])
)