CREATE TABLE [dbo].[LIKE_MOVIES]
(
	[ID] INT NOT NULL IDENTITY(1, 1) UNIQUE, 
    [ID_USUARIO] INT NOT NULL, 
    [ID_MOVIE] INT NOT NULL, 
    [COMENTARIO] VARCHAR(MAX) NULL, 
    PRIMARY KEY ([ID_MOVIE], [ID_USUARIO]), 
    CONSTRAINT [FK_LIKES_MOVIES_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIO]([ID]), 
    CONSTRAINT [FK_LIKES_MOVIES_MOVIE] FOREIGN KEY ([ID_MOVIE]) REFERENCES [MOVIE]([ID])
)
