CREATE TABLE [dbo].[LIKE_LOCAL]
(
	[ID] INT NOT NULL IDENTITY(1, 1) UNIQUE, 
    [ID_USUARIO] INT NOT NULL, 
    [ID_LOCAL] INT NOT NULL, 
    [COMENTARIO] VARCHAR(MAX) NULL, 
    PRIMARY KEY ([ID_LOCAL], [ID_USUARIO]), 
    CONSTRAINT [FK_LIKE_LOCAL_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIO]([ID]), 
    CONSTRAINT [FK_LIKE_LOCAL_LOCAL] FOREIGN KEY ([ID_LOCAL]) REFERENCES [LOCAL]([ID])
)

