CREATE TABLE [dbo].[LIKE_GENERO]
(
	[ID] INT NOT NULL IDENTITY(1, 1) UNIQUE, 
    [ID_USUARIO] INT NOT NULL, 
    [ID_GENERO] INT NOT NULL, 
    PRIMARY KEY ([ID_GENERO], [ID_USUARIO]), 
    CONSTRAINT [FK_LIKES_GENERO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIO]([ID]), 
    CONSTRAINT [FK_LIKES_GENERO_MOVIE] FOREIGN KEY ([ID_GENERO]) REFERENCES [GENERO]([ID])
)

