CREATE TABLE [dbo].[LOCAL]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[ID_CRIADOR_PAGINA] INT NOT NULL,
    [ENDERECO] VARCHAR(150) NULL, 
    [NOME] VARCHAR(50) NOT NULL, 
    [DESCRICAO] NCHAR(10) NULL, 
    [LINK] VARCHAR(50) NULL, 
    CONSTRAINT [FK_LOCAL_USUARIO] FOREIGN KEY ([ID_CRIADOR_PAGINA]) REFERENCES [USUARIO]([ID]), 
    
)
