CREATE TABLE [dbo].[MOVIE]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [ID_CRIADOR_PAGINA] INT NOT NULL, 
    [TITULO] VARCHAR(100) NOT NULL, 
    [TIPO] INT NOT NULL, 
    [TEMPORADAS] INT NULL, 
    [EPISODIOS] INT NULL, 
    [DURACAO] TIME NULL, 
    [CLASSIFICACAO] VARCHAR(30) NULL, 
    [LINK_FOTO_CAPA] VARCHAR(50) NULL, 
    CONSTRAINT [FK_MOVIE_USUARIO] FOREIGN KEY ([ID_CRIADOR_PAGINA]) REFERENCES [USUARIO]([ID]) 
)
