CREATE TABLE [dbo].[MOVIE_GENERO]
(
	[ID] INT NOT NULL  IDENTITY(1, 1) UNIQUE, 
    [ID_MOVIE] INT NOT NULL, 
    [ID_GENERO] INT NOT NULL, 
    PRIMARY KEY ([ID_GENERO], [ID_MOVIE]), 
    CONSTRAINT [FK_MOVIE_GENERO_MOVIE] FOREIGN KEY ([ID_MOVIE]) REFERENCES [MOVIE]([ID]), 
    CONSTRAINT [FK_MOVIE_GENERO_GENERO] FOREIGN KEY ([ID_GENERO]) REFERENCES [GENERO]([ID])
)
