CREATE TABLE [dbo].[POSTAGEM]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [LOCALIZACAO] VARCHAR(150) NULL, 
    [ID_USUARIO] INT NOT NULL, 
    [DATA_HORA] DATETIME NOT NULL, 
    [ID_MOVIE] INT NULL, 
    [ID_LOCAL] INT NULL, 
    [TEXTO] VARCHAR(MAX) NULL, 
    [ID_POSTAGEM] INT NULL, 
    CONSTRAINT [FK_POSTAGEM_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIO]([ID]), 
    CONSTRAINT [FK_POSTAGEM_MOVIE] FOREIGN KEY ([ID_MOVIE]) REFERENCES [MOVIE]([ID]), 
    CONSTRAINT [FK_POSTAGEM_LOCAL] FOREIGN KEY ([ID_LOCAL]) REFERENCES [LOCAL]([ID]), 
    CONSTRAINT [FK_POSTAGEM_POSTAGEM] FOREIGN KEY ([ID_POSTAGEM]) REFERENCES [POSTAGEM]([ID])
)
