CREATE TABLE [dbo].[USUARIO]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [NOME] VARCHAR(50) NOT NULL, 
    [SOBRENOME] VARCHAR(30) NOT NULL, 
    [SENHA] VARCHAR(50) NOT NULL, 
    [ENDERECO] VARCHAR(150) NOT NULL, 
    [DETALHES] VARCHAR(MAX) NULL, 
    [LINK_FOTO] VARCHAR(50) NULL, 
    [LOGIN] VARCHAR(20) NOT NULL UNIQUE	
)
